name: "Greet With A Random Meme"
on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]


jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: memes on pull_request_target
        uses: deep5050/memes-on-pull_request_target-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
